"""remove field from homolog

Revision ID: 00cffc86edba
Revises: bc3a95f66711
Create Date: 2022-01-21 13:05:23.431256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00cffc86edba'
down_revision = 'bc3a95f66711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homolog', 'srednica')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
