"""badania ups

Revision ID: 30cfe63241ce
Revises: f48d7d837146
Create Date: 2022-01-24 12:08:06.081704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30cfe63241ce'
down_revision = 'f48d7d837146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badania', sa.Column('cisnienie', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('badania', 'cisnienie')
    # ### end Alembic commands ###
