"""badania

Revision ID: 927d234220f2
Revises: c2b5adda5ce6
Create Date: 2022-01-27 14:07:21.179266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927d234220f2'
down_revision = 'c2b5adda5ce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nr_badania', sa.Column('zbiornik', sa.Integer(), nullable=True))
    op.drop_constraint('fk_nr_badania_zbiorniki_id_nr_badania', 'nr_badania', type_='foreignkey')
    op.create_foreign_key('fk_nr_badania_zbiorniki_id_zbiornik', 'nr_badania', 'zbiorniki', ['zbiornik'], ['id'])
    op.drop_column('nr_badania', 'nr_badania')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nr_badania', sa.Column('nr_badania', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_nr_badania_zbiorniki_id_zbiornik', 'nr_badania', type_='foreignkey')
    op.create_foreign_key('fk_nr_badania_zbiorniki_id_nr_badania', 'nr_badania', 'zbiorniki', ['nr_badania'], ['id'])
    op.drop_column('nr_badania', 'zbiornik')
    # ### end Alembic commands ###
