"""remove field from homolog

Revision ID: bc25b68c37e1
Revises: 00cffc86edba
Create Date: 2022-01-24 09:32:41.374809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc25b68c37e1'
down_revision = '00cffc86edba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
