"""Change nazwa to users

Revision ID: bc3a95f66711
Revises: 8bd71889ac2b
Create Date: 2022-01-21 09:21:15.362084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3a95f66711'
down_revision = '8bd71889ac2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rodzaje', 'rodzaj',  nullable=False, new_column_name='nazwa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rodzaje', 'nazwa',  nullable=False, new_column_name='rodzaj')
    # ### end Alembic commands ###
