"""badania

Revision ID: c2b5adda5ce6
Revises: 823e90fcb8ec
Create Date: 2022-01-27 13:55:18.397500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b5adda5ce6'
down_revision = '823e90fcb8ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
