"""test zb

Revision ID: cf7d60b3a264
Revises: bc25b68c37e1
Create Date: 2022-01-24 09:34:52.197719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf7d60b3a264'
down_revision = 'bc25b68c37e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
