"""zb

Revision ID: f0bd502757f7
Revises: cf7d60b3a264
Create Date: 2022-01-24 09:58:44.619667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0bd502757f7'
down_revision = 'cf7d60b3a264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
