"""badania

Revision ID: f48d7d837146
Revises: f0bd502757f7
Create Date: 2022-01-24 12:02:34.744012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f48d7d837146'
down_revision = 'f0bd502757f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
